export const GET_CURRENT_WEATHER_BY_CITY_NAME = "GET_CURRENT_WEATHER_BY_CITY_NAME";
export const GET_WHEATHER_FORECAST_FOR_FOUR_DAYS = "GET_WHEATHER_FORECAST_FOR_FIVE_CITIES";
export const CHANGE_UNIT = "CHANGE_UNIT";
export const SET_LOADING = "SET_LOADING";
export const SET_OFF_LOADING = "SET_OFF_LOADING";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

