export const GET_CURRENT_WEATHER_BY_CITY_NAME = "GET_CURRENT_WEATHER_BY_CITY_NAME";
export const GET_WHEATHER_FORECAST_FOR_FIVE_CITIES = "GET_WHEATHER_FORECAST_FOR_FIVE_CITIES";
export const GET_CURRENT_WEATHER_BY_CITY_NAME_SELECT_UNIT = "GET_CURRENT_WEATHER_BY_CITY_NAME_SELECT_UNIT";


